// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `heavy_image_logic`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> rustHeavyWorkAsync() =>
    RustLib.instance.api.crateApiSimpleRustHeavyWorkAsync();

String rustHeavyWorkSync() =>
    RustLib.instance.api.crateApiSimpleRustHeavyWorkSync();

Future<Uint8List> processImageHeavy({required List<int> imageData}) =>
    RustLib.instance.api.crateApiSimpleProcessImageHeavy(imageData: imageData);

Future<Uint8List> applyFilterAsync({required List<int> imageData}) =>
    RustLib.instance.api.crateApiSimpleApplyFilterAsync(imageData: imageData);

Uint8List applyFilterSync({required List<int> imageData}) =>
    RustLib.instance.api.crateApiSimpleApplyFilterSync(imageData: imageData);
